version: '3.9'
services:
  mydb:
    image: postgres:15-alpine
    environment:
    - POSTGRES_PASSWORD=secret
    volumes:
    - vipdb:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d
  
  web:
    image: web:alpine
    init: true
    ports:
    - 80
    volumes:
    - .:/www
    command: httpd -f -v -h /www

volumes:
  vipdb: