version: '3.9'
services:
  proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock

  mydb:
    image: postgres:15-alpine
    environment:
    - POSTGRES_PASSWORD=secret
    volumes:
    - vipdb:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d
  
  web:
    #image: web:alpine
    build:
      context: .
      dockerfile: Dockerfile.alpine
      tags:
      - web:alpine
      - lalyos/web:alpine

    init: true
    environment:
      - VIRTUAL_HOST=www.lvh.me
    ports:
    - 80

volumes:
  vipdb: