FROM alpine:3.17

RUN apk add \
  bash \
  busybox-extras-openrc \
  postgresql15-client

COPY index.html /www/
COPY cgi-bin /www/cgi-bin/
RUN chmod +x /www/cgi-bin/*
CMD [  "httpd","-f","-v","-h","/www"  ]